### ISSUE TITLE
Desperately looking for a good workflow

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#36]
Hello Alexander,

I have a question not directly related to BBE.
If it is not the right place to ask it, please do not hesitate to close the issue ;)

Here is my question:
I'm searching for a methodology/workflow to update the templates of my sites (of course made with Bl4nk) after they were going live.
For the moment, when I'm asked to adjust the template:
- I made a backup of the site
- install it locally
- adjust the parameters to make Node workin properly
- apply changes
- compile
- test
- make another backup
- replace the live site with the new one
pfiu!

Very tedious not to mention that I have to keep node modules and sass folders in the template folder. 

I'm sure there is a more efficient way (involving github ?).

Thank you for your hints

Regards

**Comment by Bloggerschmidt** [comment]
Hey Delemo, thanks for your question. If you're running node.js on your live server you can do these steps automatically in the background. Otherwise you have the procedure like above. If you only do small changes in css, maybe it is recommend to create a simple custom.css file and link it with your template. In a time when you develop local again, you can merge this css to your sass. In some cases it could be usefull only to develop local and upload the distribution (build folder) without the developing files. The folder 'node modules' shouldn't be uploaded. Hope it helps.

**Comment by Wtellos** [comment]
Is it possible to embed a php LESS/SASS compiler in the template's css folder and make the changes online?

**Comment by Delemo** [comment]
Thank you for advices

**Comment by Bloggerschmidt** [comment]
@Wtellos Yes. If you're running node.js on your live server you can compile on the fly. `gulp watch` is the hint.
